apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-app-blue 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-app-blue 
    spec:
      containers:
      - name: flask-app
        image: praveendevopsnexus/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
