apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${DEPLOYMENT}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT}
    spec:
      containers:
      - name: flask-app
        image: praveendevopsnexus/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

